image: Visual Studio 2019

configuration: Release

environment:
  GITHUB_TOKEN: <your_token_here>
  SONAR_TOKEN: <your_token_here>

before_build:
  - cmd: nuget restore your_solution.sln

build_script:
  - cmd: msbuild /p:Configuration=Release your_solution.sln
  - cmd: dotnet tool install --global dotnet-sonarscanner
  - cmd: dotnet-sonarscanner begin /k:"jcdd1_aplicacionBD" /o:"loscalidosos" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="%SONAR_TOKEN%"
  - cmd: msbuild /p:Configuration=Release your_solution.sln
  - cmd: dotnet-sonarscanner end /d:sonar.login="%SONAR_TOKEN%"

artifacts:
  - path: 'path\to\your\build\artifacts\**\*'
    name: Build Artifacts

cache:
  - '%LOCALAPPDATA%\NuGet\Cache' # Cache NuGet packages to speed up builds
  - 'packages -> **\packages.config' # More specific cache path

on_success:
  - echo Build succeeded!

on_failure:
  - echo Build failed!
